-- MySQL Script generated by MySQL Workbench
-- Wed Apr 25 23:45:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gudderidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gudderidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gudderidb` DEFAULT CHARACTER SET utf8 ;
USE `gudderidb` ;

-- -----------------------------------------------------
-- Table `gudderidb`.`Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gudderidb`.`Artist` ;

CREATE TABLE IF NOT EXISTS `gudderidb`.`Artist` (
  `artistId` INT NOT NULL AUTO_INCREMENT,
  `artistName` VARCHAR(50) NOT NULL,
  `artistNameKana` VARCHAR(100) NULL,
  `createdAt` DATETIME(3) NOT NULL,
  `createdBy` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`artistId`),
  UNIQUE INDEX `uq_artistName` (`artistName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gudderidb`.`Live`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gudderidb`.`Live` ;

CREATE TABLE IF NOT EXISTS `gudderidb`.`Live` (
  `liveId` INT NOT NULL AUTO_INCREMENT,
  `artistId` INT NOT NULL,
  `liveName` VARCHAR(50) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL,
  `createdBy` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`liveId`),
  INDEX `fk_artistId_idx` (`artistId` ASC),
  UNIQUE INDEX `uq_artistId_liveName` (`artistId` ASC, `liveName` ASC),
  CONSTRAINT `fk_artistId`
    FOREIGN KEY (`artistId`)
    REFERENCES `gudderidb`.`Artist` (`artistId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gudderidb`.`LiveSchedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gudderidb`.`LiveSchedule` ;

CREATE TABLE IF NOT EXISTS `gudderidb`.`LiveSchedule` (
  `liveScheduleId` INT NOT NULL AUTO_INCREMENT,
  `liveId` INT NOT NULL,
  `livePlace` VARCHAR(255) NOT NULL,
  `livePrefectureCode` INT NOT NULL,
  `liveDate` DATETIME(3) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL,
  `createdBy` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`liveScheduleId`),
  INDEX `fk_liveId_idx` (`liveId` ASC),
  UNIQUE INDEX `uq_liveId_liveDate` (`liveId` ASC, `liveDate` ASC),
  CONSTRAINT `fk_liveId`
    FOREIGN KEY (`liveId`)
    REFERENCES `gudderidb`.`Live` (`liveId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gudderidb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gudderidb`.`User` ;

CREATE TABLE IF NOT EXISTS `gudderidb`.`User` (
  `userId` INT NOT NULL,
  `nickName` VARCHAR(10) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL,
  `createdBy` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gudderidb`.`UserInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gudderidb`.`UserInformation` ;

CREATE TABLE IF NOT EXISTS `gudderidb`.`UserInformation` (
  `userInformationId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `messageType` INT NOT NULL,
  `readFlag` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL,
  `createdBy` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`userInformationId`),
  INDEX `fk_userId_idx` (`userId` ASC),
  CONSTRAINT `fk_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `gudderidb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
