-- MySQL Script generated by MySQL Workbench
-- Fri Apr 13 09:10:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gudderidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gudderidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gudderidb` DEFAULT CHARACTER SET utf8 ;
USE `gudderidb` ;

-- -----------------------------------------------------
-- Table `gudderidb`.`Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gudderidb`.`Artist` ;

CREATE TABLE IF NOT EXISTS `gudderidb`.`Artist` (
  `artistId` INT NOT NULL AUTO_INCREMENT,
  `artistName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`artistId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gudderidb`.`Live`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gudderidb`.`Live` ;

CREATE TABLE IF NOT EXISTS `gudderidb`.`Live` (
  `liveId` INT NOT NULL AUTO_INCREMENT,
  `liveName` VARCHAR(50) NOT NULL,
  `artistId` INT NOT NULL,
  PRIMARY KEY (`liveId`),
  INDEX `fk_artistId_idx` (`artistId` ASC),
  CONSTRAINT `fk_artistId`
    FOREIGN KEY (`artistId`)
    REFERENCES `gudderidb`.`Artist` (`artistId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gudderidb`.`LiveSchedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gudderidb`.`LiveSchedule` ;

CREATE TABLE IF NOT EXISTS `gudderidb`.`LiveSchedule` (
  `liveScheduleId` INT NOT NULL AUTO_INCREMENT,
  `liveId` INT NOT NULL,
  `livePlace` VARCHAR(255) NOT NULL,
  `liveDate` DATE NOT NULL,
  `livePrefectureCode` INT NOT NULL,
  PRIMARY KEY (`liveScheduleId`),
  INDEX `fk_liveId_idx` (`liveId` ASC),
  CONSTRAINT `fk_liveId`
    FOREIGN KEY (`liveId`)
    REFERENCES `gudderidb`.`Live` (`liveId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
